repos: []
  # - repo: local
  #   hooks:
  #     - id: format
  #       name: Format code
  #       entry: poetry run format
  #       language: system
  #       pass_filenames: false
  #       always_run: true
