version: "3"
services:
  proxy:
    image: caddy:alpine
    network_mode: "host"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  db:
    image: postgres:17
    container_name: canonical-cla-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    network_mode: "host"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: canonical-cla-redis
    network_mode: "host"

  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: canonical-cla-smtp4dev
    ports:
      - "7999:80"
      - "2525:25"
    environment:
      - RelayOptions__Login=user
      - RelayOptions__Password=password
volumes:
  postgres-data:
  caddy_data:
  caddy_config:
